In [6]:
from google.colab import drive

In [8]:
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import pandas as pd

In [10]:
data=pd.read_csv('/content/drive/MyDrive/Samplework/kleiba/creditcard.csv')

In [11]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [14]:
data.sample()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
60144,49177.0,-0.980184,-3.647154,-1.56555,1.069753,-1.441319,-1.010827,1.964756,-0.663317,-0.169127,...,0.664813,-0.806462,-1.127398,0.502077,0.086952,0.946488,-0.343847,0.196682,1199.0,0.0

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212237 entries, 0 to 212236
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    212237 non-null  float64
 1   V1      212237 non-null  float64
 2   V2      212237 non-null  float64
 3   V3      212237 non-null  float64
 4   V4      212237 non-null  float64
 5   V5      212237 non-null  float64
 6   V6      212237 non-null  float64
 7   V7      212237 non-null  float64
 8   V8      212237 non-null  float64
 9   V9      212237 non-null  float64
 10  V10     212237 non-null  float64
 11  V11     212237 non-null  float64
 12  V12     212237 non-null  float64
 13  V13     212237 non-null  float64
 14  V14     212237 non-null  float64
 15  V15     212237 non-null  float64
 16  V16     212237 non-null  float64
 17  V17     212237 non-null  float64
 18  V18     212236 non-null  float64
 19  V19     212236 non-null  float64
 20  V20     212236 non-null  float64
 21  V21     212236 non-null  float64
 22  V22     212236 non-null  float64
 23  V23     212236 non-null  float64
 24  V24     212236 non-null  float64
 25  V25     212236 non-null  float64
 26  V26     212236 non-null  float64
 27  V27     212236 non-null  float64
 28  V28     212236 non-null  float64
 29  Amount  212236 non-null  float64
 30  Class   212236 non-null  float64
dtypes: float64(31)
memory usage: 50.2 MB

In [16]:
data['Class'].value_counts()

0.0    211842
1.0       394
Name: Class, dtype: int64

In [17]:
#This Dataset is highly unblanced
#0 --> Normal Transaction
#1 --> fraudulent transaction
#The first line of code creates a new dataframe called "legit" by selecting only the rows from the original "credit_card_data" dataframe where the "Class" label is equal to 0. In other words, it filters out all transactions labeled as fraudulent (Class == 1) and keeps only the legitimate transactions (Class == 0).
#The second line of code creates a new dataframe called "fraud" by selecting only the rows from the original "credit_card_data" dataframe where the "Class" label is equal to 1. This filters out all legitimate transactions and keeps only the fraudulent transactions.
#By separating the data into two dataframes, it becomes easier to analyze and compare the characteristics of legitimate and fraudulent transactions separately. This can be useful for identifying patterns or features that are more common in fraudulent transactions, which can then be used to develop models for fraud detection.

In [18]:
legit = data[data.Class==0]
fraud = data[data['Class']==1]

In [20]:
fraud['Class']

541       1.0
623       1.0
4920      1.0
6108      1.0
6329      1.0
         ...
203700    1.0
204064    1.0
204079    1.0
204503    1.0
208651    1.0
Name: Class, Length: 394, dtype: float64

In [21]:
# statistical measures of the data
legit.Amount.describe()

count    211842.000000
mean         90.023273
std         248.295627
min           0.000000
25%           6.000000
50%          23.090000
75%          79.580000
max       19656.530000
Name: Amount, dtype: float64

In [23]:
'''count is total number of transactions in the dataset that have a valid "Amount" value (i.e., non-missing values).
mean is the average transaction amount for all the transactions in the dataset.
std is the standard deviation of the transaction amounts. It is a measure of how spread out the transaction amounts are from the mean.
min is the smallest transaction amount in the dataset.
max is the largest transaction amount in the dataset. '''

'count is total number of transactions in the dataset that have a valid "Amount" value (i.e., non-missing values).\n#mean is the average transaction amount for all the transactions in the dataset. \n#std is the standard deviation of the transaction amounts. It is a measure of how spread out the transaction amounts are from the mean. \nmin is the smallest transaction amount in the dataset. \nmax is the largest transaction amount in the dataset. '

In [24]:
fraud.Amount.describe()

count     394.000000
mean      123.172970
std       256.841767
min         0.000000
25%         1.000000
50%        13.385000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [26]:
# compare the values for both transactions
data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,74434.805756,-0.071979,-0.011843,0.269566,0.051453,-0.079723,0.042694,-0.025899,0.009267,0.011543,...,0.014487,-0.012409,-0.035454,-0.013204,0.002852,0.049762,0.004184,0.000442,0.001409,90.023273
1.0,62970.449239,-5.564086,4.145138,-7.653811,4.735781,-4.009483,-1.393320,-6.501846,0.664570,-2.742972,...,0.394589,0.778108,-0.012420,-0.048604,-0.067137,0.065962,0.038256,0.182273,0.060390,123.172970

In [27]:
legit_sample = legit.sample(n=492) #492 fraud transaction
new_df = pd.concat([legit_sample,fraud],axis=0)
new_df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
96594,65840.0,1.112988,0.101178,0.842112,1.125521,-0.543483,-0.083177,-0.372726,0.268404,0.103163,...,-0.122274,-0.434206,0.180548,0.141080,0.109649,-0.601364,0.038817,0.019120,0.99,0.0
132527,80018.0,1.004890,-0.563441,-0.102489,-0.095199,-0.210319,-0.091023,0.073651,-0.153703,0.264198,...,-0.214925,-1.021586,-0.170735,-0.946711,0.146616,0.807563,-0.099197,0.034140,192.50,0.0
177526,123214.0,0.290769,0.975297,-0.630368,1.019988,0.638119,0.042240,0.337009,-1.738695,-0.464542,...,1.596750,-0.200581,-0.304734,-0.487367,1.003555,-0.257450,0.260890,0.243975,28.00,0.0
200571,133488.0,1.850680,-0.801960,-0.404947,0.366179,-0.815854,-0.027806,-0.806767,0.205806,1.252468,...,0.213415,0.613270,0.088093,-0.376164,-0.355069,0.573727,-0.040599,-0.054385,64.99,0.0
210115,137847.0,0.050794,0.858237,0.229352,-0.618472,0.474722,-1.037323,1.018586,-0.200411,-0.039319,...,-0.268587,-0.596417,0.056365,-0.116784,-0.467704,0.147275,0.246383,0.096147,5.38,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203700,134928.0,1.204934,3.238070,-6.010324,5.720847,1.548400,-2.321064,-0.781880,0.076619,-2.976249,...,0.098341,-0.845866,-0.031228,0.421146,0.388361,0.056035,0.491828,0.340847,0.00,1.0
204064,135095.0,0.232512,0.938944,-4.647780,3.079844,-1.902655,-1.041408,-1.020407,0.547069,-1.105990,...,0.911373,1.042929,0.999394,0.901260,-0.452093,0.192959,0.180859,-0.029315,345.00,1.0
204079,135102.0,1.862102,-0.124052,-1.989752,0.382609,0.473032,-0.674517,0.298621,-0.282416,0.802053,...,-0.204158,-0.511441,0.077874,0.388335,0.007896,-0.120980,-0.019579,0.006155,108.51,1.0
204503,135314.0,-3.158990,1.765452,-3.390168,0.987410,-1.509930,-1.280952,-2.719557,0.718325,-1.660183,...,1.120533,1.605085,-0.618637,-0.251283,-0.240528,-0.004327,-0.235477,0.018129,84.28,1.0
208651,137211.0,0.630579,1.183631,-5.066283,2.179903,-0.703376,-0.103614,-3.490350,1.094734,-0.717418,...,0.621622,0.043807,0.102711,-0.601505,0.127371,-0.163009,0.853792,0.356503,39.45,1.0

In [28]:
new_df['Class'].value_counts()

0.0    492
1.0    394
Name: Class, dtype: int64

In [29]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,74877.075203,0.090652,-0.029516,0.315336,0.084673,-0.126457,0.009747,-0.044967,0.050677,-0.051934,...,0.008576,-0.017667,-0.026097,0.016184,-0.007300,0.028315,0.002849,-0.011999,-0.004906,78.69561
1.0,62970.449239,-5.564086,4.145138,-7.653811,4.735781,-4.009483,-1.393320,-6.501846,0.664570,-2.742972,...,0.394589,0.778108,-0.012420,-0.048604,-0.067137,0.065962,0.038256,0.182273,0.060390,123.17297

In [30]:
X = new_df.drop(columns='Class', axis=1)
Y = new_df['Class']

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [32]:
model=LogisticRegression() #model training

In [33]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9590395480225988

In [34]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.949438202247191